<a href="https://colab.research.google.com/github/jmuryawan/sqlite_dataexploration/blob/main/sqlite_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd
import sqlite3

In [67]:
# 1. Connecting to SQLite database
conn = sqlite3.connect('database.db')

In [68]:
# 2. Creating a pandas dataframe
df = pd.read_csv('Electric_Vehicle_Population_Data.csv')

In [69]:
df

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,JTMAB3FV3P,Kitsap,Seabeck,WA,98380.0,2023,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42.0,0.0,35.0,240684006,POINT (-122.8728334 47.5798304),PUGET SOUND ENERGY INC,5.303509e+10
1,1N4AZ1CP6J,Kitsap,Bremerton,WA,98312.0,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151.0,0.0,35.0,474183811,POINT (-122.6961203 47.5759584),PUGET SOUND ENERGY INC,5.303508e+10
2,5YJ3E1EA4L,King,Seattle,WA,98101.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,266.0,0.0,43.0,113120017,POINT (-122.3340795 47.6099315),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,1N4AZ0CP8E,King,Seattle,WA,98125.0,2014,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,108188713,POINT (-122.304356 47.715668),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
4,1G1FX6S00H,Thurston,Yelm,WA,98597.0,2017,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238.0,0.0,20.0,176448940,POINT (-122.5715761 46.9095798),PUGET SOUND ENERGY INC,5.306701e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205434,1N4BZ1CV2N,Chelan,Peshastin,WA,98847.0,2022,NISSAN,LEAF,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,12.0,187384494,POINT (-120.6051696 47.5510173),PUD NO 1 OF CHELAN COUNTY,5.300796e+10
205435,1FTVW1EV0P,Snohomish,Everett,WA,98208.0,2023,FORD,F-150,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,44.0,255036386,POINT (-122.2032349 47.8956271),PUGET SOUND ENERGY INC,5.306104e+10
205436,5YJXCDE22H,Spokane,Cheney,WA,99004.0,2017,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,200.0,0.0,6.0,221631588,POINT (-117.5836098 47.4951312),BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||...,5.306301e+10
205437,5YJ3E1EA3J,King,Vashon,WA,98070.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,34.0,336983496,POINT (-122.466938 47.429244),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
205438,7SAYGDEE7P,Spokane,Spokane,WA,99208.0,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,6.0,228335040,POINT (-117.4268937 47.7323627),BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||...,5.306301e+10

In [70]:
# 3. Saving dataframe to the SQlite database
df.to_sql('cars', conn, if_exists='replace', index=False)

205439

In [72]:
## 4. Querying the table ##

In [73]:
# Query 1: Select all records based on a specific filter of your choice
query1 = 'SELECT Make, State FROM cars'
result1_df = pd.read_sql(query1, conn)
print(result1_df)

             Make State
0          TOYOTA    WA
1          NISSAN    WA
2           TESLA    WA
3          NISSAN    WA
4       CHEVROLET    WA
...           ...   ...
205434     NISSAN    WA
205435       FORD    WA
205436      TESLA    WA
205437      TESLA    WA
205438      TESLA    WA

[205439 rows x 2 columns]

In [75]:
# Query 2: Count the number of records that meet a certain condition
## query2 = 'SELECT COUNT * FROM cars WHERE Model Year = 2020' > didn't work, can't figure out why > update: use '' or [] for column names with a space because sql/sqlite can't read it then
query2 = """
SELECT COUNT(*) AS total_count_model
FROM cars
WHERE Model = 'LEAF';
"""
result2_df = pd.read_sql(query2, conn)
print(result2_df)

   total_count_model
0              13488

In [76]:
# Query 3: Group the data by a specific column and calculate a summary statistic for each group

query3 = """
SELECT State,
AVG(`Electric Range`) AS average_electric_range,
MAX(`Electric Range`) AS max_electric_range,
MIN(`Electric Range`) AS min_electric_range
FROM cars
GROUP BY State;
"""

result3_df = pd.read_sql(query3, conn)
print(result3_df)

   State  average_electric_range  max_electric_range  min_electric_range
0     AE               16.000000                16.0                16.0
1     AK                0.000000                 0.0                 0.0
2     AL               77.500000               259.0                 0.0
3     AR              157.333333               322.0                 0.0
4     AZ               34.769231               200.0                 0.0
5     BC              126.500000               200.0                53.0
6     CA               45.215517               337.0                 0.0
7     CO               37.588235               215.0                 0.0
8     CT               64.875000               322.0                 0.0
9     DC              183.000000               215.0               151.0
10    DE                0.000000                 0.0                 0.0
11    FL               56.363636               291.0                 0.0
12    GA               70.200000               308.0                 0.0
13    HI               83.333333               238.0                 0.0
14    IA              249.000000               249.0               249.0
15    ID                8.800000                25.0                 0.0
16    IL               68.230769               322.0                 0.0
17    IN               81.000000               210.0                 0.0
18    KS               16.750000                32.0                 0.0
19    KY                6.600000                33.0                 0.0
20    LA              151.000000               238.0                 0.0
21    MA                0.000000                 0.0                 0.0
22    MD               51.812500               291.0                 0.0
23    MI               21.000000                42.0                 0.0
24    MN              220.000000               220.0               220.0
25    MO              159.333333               322.0                 0.0
26    NC               33.312500               215.0                 0.0
27    NE               16.500000                33.0                 0.0
28    NH              308.000000               308.0               308.0
29    NJ               39.750000               220.0                 0.0
30    NM               12.500000                25.0                 0.0
31    NV              157.555556               322.0                 0.0
32    NY               80.571429               322.0                 0.0
33    OH               63.500000               215.0                 0.0
34    OK                0.000000                 0.0                 0.0
35    OR               76.800000               322.0                 0.0
36    PA               16.500000                41.0                 0.0
37    RI               13.666667                22.0                 0.0
38    SC               17.428571                53.0                 0.0
39    TX               91.307692               322.0                 0.0
40    UT               83.500000               259.0                 0.0
41    VA               63.396552               330.0                 0.0
42    WA               52.148769               337.0                 0.0
43    WI              220.000000               220.0               220.0
44    WY                0.000000                 0.0                 0.0

In [77]:
# Query 4: Sort the records based on a numerical or categorical field and return a limited set of results (e.g., top 5 records).
query4 = """
SELECT *
FROM cars
ORDER BY 'Model Year' DESC
LIMIT 3;
"""

result4_df = pd.read_sql(query4, conn)
print(result4_df)

   VIN (1-10)  County       City State  Postal Code  Model Year    Make  \
0  JTMAB3FV3P  Kitsap    Seabeck    WA      98380.0        2023  TOYOTA
1  1N4AZ1CP6J  Kitsap  Bremerton    WA      98312.0        2018  NISSAN
2  5YJ3E1EA4L    King    Seattle    WA      98101.0        2020   TESLA

        Model                   Electric Vehicle Type  \
0  RAV4 PRIME  Plug-in Hybrid Electric Vehicle (PHEV)
1        LEAF          Battery Electric Vehicle (BEV)
2     MODEL 3          Battery Electric Vehicle (BEV)

  Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0           Clean Alternative Fuel Vehicle Eligible            42.0
1           Clean Alternative Fuel Vehicle Eligible           151.0
2           Clean Alternative Fuel Vehicle Eligible           266.0

   Base MSRP  Legislative District  DOL Vehicle ID  \
0        0.0                  35.0       240684006
1        0.0                  35.0       474183811
2        0.0                  43.0       113120017

                  Vehicle Location  \
0  POINT (-122.8728334 47.5798304)
1  POINT (-122.6961203 47.5759584)
2  POINT (-122.3340795 47.6099315)

                               Electric Utility  2020 Census Tract
0                        PUGET SOUND ENERGY INC       5.303509e+10
1                        PUGET SOUND ENERGY INC       5.303508e+10
2  CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303301e+10

In [78]:
conn.close()